### ISSUE TITLE
右下角的回到顶部的css挂了

### ISSUE THREAD

**Issue by canoziia** [MagShadow/MagShadow.github.io#1]
![image](https://github.com/MagShadow/MagShadow.github.io/assets/54797411/049c52ce-bbfa-4f6e-b9f9-6bc28492b7fb)

**Comment by MagShadow** [comment]
我在PC上和手机上看着都正常？会卡一下，然后加载出来。还是感谢提出建议！

**Comment by canoziia** [comment]
我今天重新看了下好像正常了，估计是当时dns抽风了或者什么
